INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('Alex', 'Martin', 0, 'manager1_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('Sam', 'Johnes', 1, 'engineer1_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('John', 'Doe', 2, 'user1_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('Patrick', 'Jane', 0, 'manager2_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('Jay', 'Carter', 1, 'engineer2_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO user (first_name, last_name, role_id, email, password) VALUES('Tommy', 'Dent', 2, 'user2_mogilev@yopmail.com', 'P@ssword1');
INSERT INTO category (name) VALUES ('Application & Services');
INSERT INTO category (name) VALUES ('Benefits & Paper Work');
INSERT INTO category (name) VALUES ('Hardware & Software');
INSERT INTO category (name) VALUES ('People Management');
INSERT INTO category (name) VALUES ('Security & Access');
INSERT INTO category (name) VALUES ('Workplaces & Facilities');
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket1', 'Description1', GETDATE(), GETDATE(), 2, 1, 0, 1, 0, 1);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket2', 'Description2', GETDATE(), GETDATE(), 2, 1, 1, 2, 1, 4);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket3', 'Description3', GETDATE(), GETDATE(), 2, 1, 2, 3, 2, 1);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket4', 'Description4', GETDATE(), GETDATE(), 2, 3, 3, 4, 3, 1);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket5', 'Description5', GETDATE(), GETDATE(), 5, 3, 4, 5, 0, 1);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket6', 'Description6', GETDATE(), GETDATE(), 5, 3, 5, 6, 1, 4);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket7', 'Description5', GETDATE(), GETDATE(), 5, 4, 6, 1, 2, 4);
INSERT INTO ticket (name, description, created_on, desired_resolution_date, assignee_id, owner_id, state_id, category_id, urgency_id, approver_id) VALUES ('Ticket8', 'Description6', GETDATE(), GETDATE(), 5, 6, 0, 2, 3, 4);